name: DockerCI-PR

on:
  pull_request:
    branches:
      - master

    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'README.md'
      - 'saveenv.sh'

jobs:

  docker-build-push:

    runs-on: ubuntu-latest
    env:
      #  DOCKER_REPO  - the docker repository name in the form: organization/repository
      DOCKER_REPO: 'retaildevcrew/webvalidate'

    steps:
    - uses: actions/checkout@v1

    - name: Login to registry
      run: |
        # Login to registry

        #    You must add the following secrets to github
        #    DOCKER_USER  - your dockerhub user name
        #    DOCKER_PAT   - the personal access token for dockerhub
       

        ## login to dockerhub
        echo "${{ secrets.DOCKER_PAT }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

    - name: Build Container
      run: docker build . --file Dockerfile-e2e --tag image

    - name: Docker Push
      run: |
        # Tag and push the docker image

        IMAGE_ID=$DOCKER_REPO

        # Tag image based on repo tag if a github label


        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.head_ref }}" | sed -e 's,.*/\(.*\),\1,')

        docker tag image $IMAGE_ID:beta
        docker push $IMAGE_ID:beta


  
